name: lyrics818 # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '1.34' # just for humans, typically '1.2+git' or '1.3.2'
summary: Generates a lyric video # 79 char long summary
description: |
  lyrics818 generates a lyric video. It expects the lyric file, fonts, background.


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:
  arm64:


parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
      - go
    build-packages:
      - build-essential
      - gcc
      - libgl1-mesa-dev
      - xorg-dev
      - libc6-dev
    override-build: |
      set -xe
      go mod download
      go build -o $SNAPCRAFT_PART_INSTALL/bin/lyrics818 ./linux

  pickers:
    # See 'snapcraft plugins'
    plugin: go
    source: https://github.com/saenuma/pickers.git
    build-snaps:
      - go
    build-packages:
      - build-essential
      - gcc
      - libgl1-mesa-dev
      - xorg-dev
      - libc6-dev
    override-build: |
      set -xe
      go mod download
      go build -o $SNAPCRAFT_PART_INSTALL/bin/fpicker ./fpicker
      go build -o $SNAPCRAFT_PART_INSTALL/bin/acpicker ./acpicker

  ff-part:
    plugin: nil
    build-packages:
      - wget
      - tar
      - unzip
    override-build: |
      set -xe
      ARCH=$(uname -m)
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/

      if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
        echo "Building for ARM64 architecture"
        wget https://storage.googleapis.com/saenuma_public/ff_arm64.tar.xz
        tar xvf ff_arm64.tar.xz -C $SNAPCRAFT_PART_INSTALL/bin/
      else
        # Check if the architecture is AMD64
        if [ "$ARCH" = "x86_64" ] || [ "$ARCH" = "amd64" ]; then
          echo "Building for AMD64 architecture"
          wget https://storage.googleapis.com/saenuma_public/ff_amd64.tar.xz
          tar xvf ff_amd64.tar.xz -C $SNAPCRAFT_PART_INSTALL/bin/
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
      fi
      rm $SNAPCRAFT_PART_INSTALL/bin/ffprobe


apps: 
  lyrics818:
    command: bin/lyrics818
    extensions: [gnome]
